// <auto-generated />
using System;
using MarketAssetPriceAPI.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketAssetPriceAPI.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.InstrumentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TickSize")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.InstrumentProviderRelation", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("InstrumentProvider", (string)null);
                });

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.ProviderDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.InstrumentProviderRelation", b =>
                {
                    b.HasOne("MarketAssetPriceAPI.Data.Models.DTOs.InstrumentDTO", null)
                        .WithMany("InstrumentProviders")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAssetPriceAPI.Data.Models.DTOs.ProviderDTO", null)
                        .WithMany("InstrumentProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.InstrumentDTO", b =>
                {
                    b.Navigation("InstrumentProviders");
                });

            modelBuilder.Entity("MarketAssetPriceAPI.Data.Models.DTOs.ProviderDTO", b =>
                {
                    b.Navigation("InstrumentProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
